- hosts: bigip
  tasks:     
  - name: Add self IP
    bigip_selfip:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      name: "10.1.10.1"
      address: "10.1.10.1"
      netmask: "255.255.255.0"
      vlan: "external"
      validate_certs: "no"
    delegate_to: localhost
