---
- hosts: bigip
  gather_facts: False
- import_playbook: roles/onboarding/bigip_device_ntp/set_ntp_server.yml 
  vars: 
    - ntp_server1: "time.apple.com" 
    - ntp_server2: "time.nist.gov"

- import_playbook: roles/onboarding/bigip_device_ntp/set_timezone.yml 
  vars:
    - timezone: "America/New_York"
...
